# Generated by Django 4.1.2 on 2022-10-09 01:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Aparelhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=11)),
                ('modelo_aparelho', models.CharField(max_length=30)),
                ('defeito_informado', models.TextField(blank=True, max_length=255, null=True)),
                ('data_entrada', models.DateField(default=datetime.date.today)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('status_servico', models.BooleanField(default=False)),
                ('nome_retirada', models.CharField(blank=True, max_length=30, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aparelho.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'aparelho',
            },
        ),
    ]
